export const errors = {
  USUARIO_EXISTENTE_VERIFICADO : "USUARIO_EXISTENTE_VERIFICADO",
  USUARIO_EXISTENTE_NO_VERIFICADO : "USUARIO_EXISTENTE_NO_VERIFICADO",
  USUARIO_NO_ADMINISTRADOR : "USUARIO_NO_ADMINISTRADOR",
  TOKEN_NO_VALIDO : "TOKEN_NO_VALIDO",
  CLAVE_IGUAL_A_ANTERIOR: "CLAVE_IGUAL_A_ANTERIOR",
  CLAVE_NO_COINCIDENTE: "CLAVE_NO_COINCIDENTE",
  ERROR_EN_EL_SERVIDOR : "ERROR_EN_EL_SERVIDOR",
  NO_ENCONTRADO : "NO_ENCONTRADO",
  SIN_AUTENTICACION : "SIN_AUTENTICACION"
}