export const CART_TYPES = {
  ADD_PRODUCT_TO_CART : "ADD_PRODUCT_TO_CART",
  DECREASE_PRODUCT_FROM_CART : "DECREASE_PRODUCT_FROM_CART",
  REMOVE_PRODUCT_FROM_CART : "REMOVE_PRODUCT_FROM_CART",
  REMOVE_ALL_PRODUCTS_FROM_CART : "REMOVE_ALL_PRODUCTS_FROM_CART",
};

export const USER_TYPES = {
  SET_CURRENT_USER : "SET_CURRENT_USER"
}